@startuml
title Client Authorization
hide unlinked
hide footbox
autonumber

actor extsys as "External System"
actor iam as "Identity And\nAccess Management"

activate extsys

extsys -> iam : Get Access Token [ITI-71]
activate iam
extsys <-- iam : Access Token
deactivate iam
@enduml

@startuml
title Account URN Resolution
hide unlinked
hide footbox
autonumber

actor extsys as "External System"
actor aim as "Account and\nIdentifier Management"

activate extsys

extsys -> aim : Resolve AccountURN by MPI-ID
activate aim
extsys <-- aim : AccountURN
deactivate aim
@enduml

@startuml
title FHIR Operation
hide unlinked
hide footbox
autonumber

actor extsys as "External System"
actor fhirserver as "FHIR Server"

activate extsys

extsys -> extsys : extract the partition name

extsys -> fhirserver : Call FHIR Operation
activate fhirserver
extsys <-- fhirserver : FHIR Result
deactivate fhirserver
@enduml
